-- Drew Tennis Scanner 6.0 Railway qualified-trade schema
-- Run this entire file once in Supabase: SQL Editor -> New query -> Run.
-- The tables are intentionally private. The Railway worker uses a server-side
-- Supabase secret key (preferred) or legacy service_role key.

create table if not exists public.worker_status (
    worker_id text primary key,
    version text not null,
    status text not null,
    started_at timestamptz,
    last_seen_at timestamptz not null default now(),
    last_cycle_id uuid,
    last_cycle_started_at timestamptz,
    last_cycle_completed_at timestamptz,
    last_cycle_duration_seconds double precision,
    last_error text,
    metrics jsonb not null default '{}'::jsonb,
    railway_deployment_id text,
    updated_at timestamptz not null default now()
);

create table if not exists public.scan_cycles (
    cycle_id uuid primary key,
    worker_id text not null,
    worker_version text not null,
    started_at timestamptz not null,
    completed_at timestamptz,
    duration_seconds double precision not null default 0,
    status text not null,
    api_events integer not null default 0,
    supported_events integer not null default 0,
    excluded_events integer not null default 0,
    markets_matched integer not null default 0,
    markets_unmatched integer not null default 0,
    player_scans integer not null default 0,
    trade_signals integer not null default 0,
    inserted_scans integer not null default 0,
    duplicate_scans integer not null default 0,
    errors jsonb not null default '[]'::jsonb,
    warnings jsonb not null default '[]'::jsonb,
    metrics jsonb not null default '{}'::jsonb
);

create table if not exists public.shadow_scans (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    scanned_at timestamptz not null,
    cycle_id uuid not null,
    worker_id text not null,
    worker_version text not null,

    event_key text not null,
    event_date date,
    event_time text,
    player text not null,
    opponent text not null,
    tournament text,
    event_type text,
    league text,
    competition_group text,
    api_source text,
    event_status text,
    event_final_result text,
    event_game_result text,
    event_serve text,
    event_state jsonb not null default '{}'::jsonb,

    market_found boolean not null default false,
    market_id text,
    market_slug text,
    market_title text,
    market_lookup_source text,
    market_match_confidence double precision,
    market_side text,
    market_price_cents double precision not null default 0,
    market_price_timestamp timestamptz,
    market_volume double precision,
    market_liquidity double precision,
    market_metadata jsonb not null default '{}'::jsonb,

    decision_status text not null,
    decision_reason text,
    stability_score double precision not null default 0,
    required_score double precision not null default 0,
    stake_pct double precision not null default 0,
    stake_amount double precision not null default 0,
    bankroll double precision not null default 0,

    data_completeness_pct double precision not null default 0,
    core_completeness_pct double precision not null default 0,
    scoring_completeness_pct double precision not null default 0,

    match_closing_set boolean,
    straight_set_closing boolean not null default false,
    deciding_set boolean not null default false,
    best_of_sets integer not null default 3,
    serving_for_match boolean not null default false,
    break_lead integer,
    serving boolean,
    tiebreak boolean,
    backed_player_games_in_set integer,
    current_game_score text,
    opponent_games_in_set integer,
    completed_sets integer,
    breaks_suffered_by_set jsonb not null default '[]'::jsonb,
    service_points_won_pct double precision,
    current_set_service_points_won_pct double precision,
    effective_service_points_won_pct double precision,
    opponent_service_points_won_pct double precision,
    opponent_current_set_service_points_won_pct double precision,
    first_serve_points_won_pct double precision,
    current_set_first_serve_points_won_pct double precision,
    first_serve_in_pct double precision,
    current_set_first_serve_in_pct double precision,
    breaks_suffered_total integer,
    current_set_breaks_suffered integer,
    break_points_created integer,
    break_points_faced integer,
    comfortable_holds_pct double precision,
    double_faults_per_service_game double precision,
    ranking integer,
    opponent_ranking integer,

    trade_key text,
    recommendation_change text,
    alert_eligible boolean not null default false,

    warnings jsonb not null default '[]'::jsonb,
    errors jsonb not null default '[]'::jsonb,
    score_parts jsonb not null default '{}'::jsonb,
    factor_availability jsonb not null default '{}'::jsonb,
    field_provenance jsonb not null default '{}'::jsonb,
    match_snapshot jsonb not null default '{}'::jsonb,

    paper_trade_status text not null default 'NOT_ENTERED',
    paper_entry_price_cents double precision,
    paper_stake_amount double precision not null default 0,
    paper_result text,
    paper_pnl double precision not null default 0,
    final_winner text,
    final_score text,
    resolved_at timestamptz,

    dedupe_key text not null unique
);

create index if not exists shadow_scans_scanned_at_idx
    on public.shadow_scans (scanned_at desc);
create index if not exists shadow_scans_event_key_idx
    on public.shadow_scans (event_key, scanned_at desc);
create index if not exists shadow_scans_decision_idx
    on public.shadow_scans (decision_status, scanned_at desc);
create index if not exists shadow_scans_player_idx
    on public.shadow_scans (player, scanned_at desc);
create index if not exists scan_cycles_started_at_idx
    on public.scan_cycles (started_at desc);

alter table public.worker_status enable row level security;
alter table public.scan_cycles enable row level security;
alter table public.shadow_scans enable row level security;

revoke all on public.worker_status from anon, authenticated;
revoke all on public.scan_cycles from anon, authenticated;
revoke all on public.shadow_scans from anon, authenticated;

grant all on public.worker_status to service_role;
grant all on public.scan_cycles to service_role;
grant all on public.shadow_scans to service_role;
grant usage, select on all sequences in schema public to service_role;

comment on table public.worker_status is 'Latest heartbeat and health summary for each Railway scanner worker.';
comment on table public.scan_cycles is 'One row per API Tennis and Polymarket shadow scan cycle.';
comment on table public.shadow_scans is 'Qualified Version 6.0 paper-trade scans only. Polymarket data is informational and no real orders are placed.';


-- Safe V5.6 -> V6.0 migration for an existing Supabase project.
alter table public.shadow_scans add column if not exists market_price_timestamp timestamptz;
alter table public.shadow_scans add column if not exists market_volume double precision;
alter table public.shadow_scans add column if not exists market_liquidity double precision;
alter table public.shadow_scans add column if not exists straight_set_closing boolean not null default false;
alter table public.shadow_scans add column if not exists deciding_set boolean not null default false;
alter table public.shadow_scans add column if not exists best_of_sets integer not null default 3;
alter table public.shadow_scans add column if not exists serving_for_match boolean not null default false;
alter table public.shadow_scans add column if not exists opponent_games_in_set integer;
alter table public.shadow_scans add column if not exists current_set_service_points_won_pct double precision;
alter table public.shadow_scans add column if not exists effective_service_points_won_pct double precision;
alter table public.shadow_scans add column if not exists opponent_service_points_won_pct double precision;
alter table public.shadow_scans add column if not exists opponent_current_set_service_points_won_pct double precision;
alter table public.shadow_scans add column if not exists current_set_first_serve_points_won_pct double precision;
alter table public.shadow_scans add column if not exists current_set_first_serve_in_pct double precision;
alter table public.shadow_scans add column if not exists current_set_breaks_suffered integer;
alter table public.shadow_scans add column if not exists break_points_created integer;
alter table public.shadow_scans add column if not exists opponent_ranking integer;
alter table public.shadow_scans add column if not exists trade_key text;
alter table public.shadow_scans add column if not exists recommendation_change text;
alter table public.shadow_scans add column if not exists alert_eligible boolean not null default false;
alter table public.shadow_scans add column if not exists final_winner text;
alter table public.shadow_scans add column if not exists final_score text;
alter table public.shadow_scans add column if not exists resolved_at timestamptz;
