-- Safe V5.6 -> V6.0 migration for an existing Supabase project.
alter table public.shadow_scans add column if not exists market_price_timestamp timestamptz;
alter table public.shadow_scans add column if not exists market_volume double precision;
alter table public.shadow_scans add column if not exists market_liquidity double precision;
alter table public.shadow_scans add column if not exists straight_set_closing boolean not null default false;
alter table public.shadow_scans add column if not exists deciding_set boolean not null default false;
alter table public.shadow_scans add column if not exists best_of_sets integer not null default 3;
alter table public.shadow_scans add column if not exists serving_for_match boolean not null default false;
alter table public.shadow_scans add column if not exists opponent_games_in_set integer;
alter table public.shadow_scans add column if not exists current_set_service_points_won_pct double precision;
alter table public.shadow_scans add column if not exists effective_service_points_won_pct double precision;
alter table public.shadow_scans add column if not exists opponent_service_points_won_pct double precision;
alter table public.shadow_scans add column if not exists opponent_current_set_service_points_won_pct double precision;
alter table public.shadow_scans add column if not exists current_set_first_serve_points_won_pct double precision;
alter table public.shadow_scans add column if not exists current_set_first_serve_in_pct double precision;
alter table public.shadow_scans add column if not exists current_set_breaks_suffered integer;
alter table public.shadow_scans add column if not exists break_points_created integer;
alter table public.shadow_scans add column if not exists opponent_ranking integer;
alter table public.shadow_scans add column if not exists trade_key text;
alter table public.shadow_scans add column if not exists recommendation_change text;
alter table public.shadow_scans add column if not exists alert_eligible boolean not null default false;
alter table public.shadow_scans add column if not exists final_winner text;
alter table public.shadow_scans add column if not exists final_score text;
alter table public.shadow_scans add column if not exists resolved_at timestamptz;
